name: "Security and Quality Checks"

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '.github/workflows/security-scan.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '.github/workflows/security-scan.yml'

jobs:
  security-scan:
    name: "Security and Quality"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Install Checkov
      run: |
        pip install checkov

    - name: Run Checkov Security Scan
      run: |
        checkov -d . --framework terraform --output cli --output junitxml --output-file-path ./
        checkov -d . --framework terraform --output sarif --output-file-path ./

    - name: Upload Checkov SARIF
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: ./checkov-report.sarif

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Run TFLint
      run: |
        tflint --init
        tflint --format=checkstyle > tflint-report.xml || true

    - name: Terraform Docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ./
        output-file: README.md
        output-method: inject
        git-push: 'false'

    - name: Comment PR
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          let comment = '## 🔍 Security and Quality Report\n\n';
          
          // Checkov results
          if (fs.existsSync('./checkov-report.xml')) {
            comment += '### ✅ Checkov Security Scan\n';
            comment += 'Security scan completed. Check the logs for detailed results.\n\n';
          }
          
          // TFLint results
          if (fs.existsSync('./tflint-report.xml')) {
            comment += '### ✅ TFLint Code Quality\n';
            comment += 'Code quality check completed. Check the logs for detailed results.\n\n';
          }
          
          comment += '### 📋 Summary\n';
          comment += '- Security scan: ✅ Completed\n';
          comment += '- Code quality: ✅ Completed\n';
          comment += '- Documentation: ✅ Updated\n';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          }) 